name: Master

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: rust:1-bullseye
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Prerequisite
        run: apt-get update && apt-get upgrade -y && apt-get install -y make sqlite3 curl ca-certificates openssl

      - name: Build
        run: make build

      - name: Test
        run: make test
