name: Master

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: rust:1-bullseye
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Prerequisite
        run: >
          apt-get update && apt-get upgrade -y && 
          apt-get install -y make sqlite3 curl ca-certificates openssl &&
          rustup component add llvm-tools-preview &&
          cargo install grcov

      - name: Build
        run: make build-dev
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "kartel-%p-%m.profraw"

      - name: Test
        run: make test
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "kartel-%p-%m.profraw"

      - name: Collect coverage
        run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "kartel-%p-%m.profraw"

      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
